version: 0.1
server:
  addr: ":5000"
  certificate: "/ssl/server.pem"
  key: "/ssl/server.key"
auth:
  token:
    realm: http://host.docker.internal:8000/auth
    service: "registry.ezileli.dev"
    issuer: "auth.registry.ezileli.dev"
    rootcertbundle: /ssl/server.pem
http:
  addr: 0.0.0.0:5000
  net: tcp
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
